config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'
  get 'dashboard/calendar'
  resources :candidates

  devise_for :users

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_attached_file :resume, styles: { thumbnail: ['100x100#', :png] }
  do_not_validate_attachment_file_type :resume#, content_type: { content_type: 'application/pdf' }

  validates :name, :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  def index
    @candidates = Candidate.all
  end

  def show
  end

  def new
    @candidate = Candidate.new
  end

  def edit
  end

  def create
    @candidate = Candidate.new(candidate_params)

    if @candidate.save
      redirect_to @candidate, notice: 'Candidate was successfully created.'
    else
      render :new
    end
  end

  def update
    if @candidate.update(candidate_params)
      redirect_to @candidate, notice: 'Candidate was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @candidate.destroy
    redirect_to candidates_url, notice: 'Candidate was successfully destroyed.'
  end

  private

  def set_candidate
    @candidate = Candidate.find(params[:id])
  end

  def candidate_params
    params.require(:candidate).permit(:name, :email, :note, :resume)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def calendar
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/candidates/_form.html.haml
= form_for @candidate do |f|
  - if @candidate.errors.any?
    #error_explanation
      %h2= "#{pluralize(@candidate.errors.count, "error")} prohibited this candidate from being saved:"
      %ul
        - @candidate.errors.full_messages.each do |msg|
          %li= msg

  = f.label :name
  = f.text_field :name

  = f.label :email

  = f.text_field :email

  = f.label :resume
  - if f.object.resume_file_name
    %p= f.object.resume_file_name
    = image_tag f.object.resume.url(:thumbnail)
  = f.file_field :resume

  = f.label :note
  = f.trix_editor :note


  .actions
    = f.submit 'Save'

%br/

app/views/candidates/edit.html.haml
%br/

%ul.breadcrumbs
  %li
    %a{:href => root_path } Home
  %li
    %a{:href => candidates_path } Candidates
  %li.disabled Edit

%h4 Edit

= render 'form'

app/views/candidates/index.html.haml
%br/

%ul.breadcrumbs
  %li
    %a{:href => root_path} Home
  %li.disabled All candidates

%h4 All candidates

= link_to new_candidate_path, class: 'button' do
  %i.fi-plus
    Add new candidate

%br/

%table.stack
  %thead
    %tr
      %th Preview
      %th Name
      %th Email
      %th
      %th

  %tbody
    - @candidates.each do |candidate|
      %tr
        %td= image_tag candidate.resume.url(:thumbnail)
        %td= candidate.name
        %td= candidate.email
        %td
          = link_to edit_candidate_path(candidate) do
            %i.fi-page-edit
        %td
          = link_to candidate, method: :delete, data: { confirm: 'Are you sure?' } do
            %i.fi-trash

%br

app/views/candidates/new.html.haml
%br/

%ul.breadcrumbs
  %li
    %a{:href => root_path } Home
  %li
    %a{:href => candidates_path } Candidates
  %li.disabled Add new

%h4 New candidate

= render 'form'

app/views/candidates/show.html.haml
%br/

%ul.breadcrumbs
  %li
    %a{:href => root_path } Home
  %li
    %a{:href => candidates_path } Candidates
  %li.disabled Show

%h5= @candidate.name
%h5= @candidate.email

%h3 Note
%p= @candidate.note.html_safe

app/views/dashboard/calendar.html.haml
%br/
#calendar

:javascript
  $('#calendar').fullCalendar({});

app/views/dashboard/index.html.haml
%h1 Dashboard#index
%p Find me in app/views/dashboard/index.html.haml

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : 'Hiring Hero'

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

    = csrf_meta_tag

  %body
    = render 'shared/topbar'

    #main-container.row.expanded
      #main-sidebar.large-2.columns.no-sides-padding.main-theme-color
        = render 'shared/sidebar'
      .large-10.columns.white-bg
        = yield

    = render 'shared/footer'

    = javascript_include_tag 'application'

app/views/layouts/devise.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : 'Hiring Hero'

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tag

  %body
    = yield

app/views/shared/_footer.html.haml
.top-bar.hiring-hero-footer
  %p.copyright © 2016 Hiring Hero, Inc. All rights reserved.

app/views/shared/_sidebar.html.haml
%ul.menu.vertical
  %li
    %a.button.align-left{:href => root_url }
      %i.fi-home.normal-style
        Dashboard
  %li
    %a.button.align-left{:href => candidates_path }
      %i.fi-folder.normal-style
        Candidates
  %li
    %a.button.align-left{:href => "#"}
      %i.fi-torsos-all.normal-style
        Hiring Managers
  %li
    %a.button.align-left{:href => dashboard_calendar_path}
      %i.fi-calendar.normal-style
        Calendar
  %li
    %a.button.align-left{:href => "#"}
      %i.fi-refresh.normal-style
        In process
  %li
    %a.button.align-left{:href => "#"}
      %i.fi-wrench.normal-style
        Interview Process Design

app/views/shared/_topbar.html.haml
.top-bar
  .top-bar-left
    %ul.dropdown.menu{"data-dropdown-menu" => ""}
      %li= image_tag("logo.png", width: '70%')

  .top-bar-right{"data-dropdown-menu" => ""}
    %ul.menu.dropdown
      %li
        - if current_user
          %a{:href => "#"}= current_user.email
          %ul.menu
            %li
              %a{ href: '#' } Settings
            %li
              = link_to('Logout', destroy_user_session_path, method: :delete)
        - else
          = link_to('Login', new_user_session_path)

  .top-bar-right
    %ul.menu
      %li
        %input{:placeholder => "Search", :type => "search"}/
      %li
        %button.button{:type => "button"} Search